module.exports = {
  BASE_URL: 'https://dev.qewam.com',
  APP_URL: 'https://dev.qewam.com',
  ECHO_HOST: 'dev.qewam.com',
  BASE_AUTH_LOGIN: 'qewam',
  BASE_AUTH_PASSWORD: 'qewam2020',
  HOTJAR_ID: '',
  HOTJAR_PRODUCTION_MODE: false,
  VUE_ANALYTICS_ID: '',
  VUE_SENTRY_DSN: 'https://@o382843.ingest.sentry.io/5212339',
  VUE_MODE: 'development',
  ENABLE_COOKIE_ACCEPT: true,
  STRIPE_API_KEY: '',
  FACEBOOK_CLIENT_ID: '',
  GOOGLE_CLIENT_ID: '',
  TWITCH_CLIENT_ID: '',
  DISCORD_CLIENT_ID: '',
  VUE_APP_I18N_LOCALE:'en',
  VUE_APP_I18N_FALLBACK_LOCALE:'en',
  REDIS_PREFIX:'local_',
  LOCIZE_VERSION: 'latest',
  LOCIZE_NAMESPACE: 'frontend',
  LOCIZE_PROJECTID: '',
  LOCIZE_APIKEY: '',
  LOCIZE_REFERENCELANGUAGE: 'en',
};
